./system_wrappers/source/Android.mk
./modules/audio_device/Android.mk
./modules/rtp_rtcp/source/Android.mk
./modules/video_coding/codecs/vp8/Android.mk
./modules/video_coding/codecs/i420/main/source/Android.mk
./modules/video_coding/utility/Android.mk
./modules/video_coding/main/source/Android.mk
./modules/video_capture/Android.mk
./modules/audio_coding/codecs/pcm16b/Android.mk
./modules/audio_coding/codecs/isac/fix/source/Android.mk
./modules/audio_coding/codecs/isac/main/source/Android.mk
./modules/audio_coding/codecs/g722/Android.mk
./modules/audio_coding/codecs/g711/Android.mk
./modules/audio_coding/codecs/ilbc/Android.mk
./modules/audio_coding/codecs/cng/Android.mk
./modules/audio_coding/neteq/Android.mk
./modules/audio_coding/main/source/Android.mk
./modules/audio_conference_mixer/source/Android.mk
./modules/audio_processing/ns/Android.mk
./modules/audio_processing/test/android/apmtest/jni/Android.mk
./modules/audio_processing/agc/Android.mk
./modules/audio_processing/aec/Android.mk
./modules/audio_processing/Android.mk
./modules/audio_processing/aecm/Android.mk
./modules/audio_processing/utility/Android.mk
./modules/media_file/source/Android.mk
./modules/video_processing/main/source/Android.mk
./modules/video_render/Android.mk
./modules/utility/source/Android.mk
./test/Android.mk
./voice_engine/test/cmd_test/Android.mk
./voice_engine/test/android/android_test/jni/Android.mk
./voice_engine/test/android/android_test/Android.mk
./voice_engine/test/auto_test/Android.mk
./voice_engine/Android.mk
./video_engine/test/android/jni/Android.mk
./video_engine/test/svmp/android/jni/Android.mk
./video_engine/test/svmp/android/Android.mk
./video_engine/test/svmp/source/Android.mk
./video_engine/test/auto_test/android/jni/Android.mk
./video_engine/test/auto_test/android/Android.mk
./video_engine/test/auto_test/source/Android.mk
./video_engine/Android.mk
./common_audio/resampler/Android.mk
./common_audio/signal_processing/Android.mk
./common_audio/vad/Android.mk
./common_video/jpeg/Android.mk
./common_video/libyuv/Android.mk
