# This file is generated by gyp; do not edit.

export builddir_name ?= trunk/webrtc/tools/out
.PHONY: all
all:
	$(MAKE) -C ../.. frame_editing_lib video_quality_analysis tools_unittests psnr_ssim_analyzer frame_editor rgba_to_i420_converter frame_analyzer force_mic_volume_max
