# This file is generated by gyp; do not edit.

export builddir_name ?= trunk/webrtc/video_engine/out
.PHONY: all
all:
	$(MAKE) -C ../.. video_engine_core video_engine_core_unittests video_tests_common libvietest vie_auto_test video_loopback svmp-fbstream libvietest_unittests
